### ISSUE TITLE
Curriculum

### ISSUE THREAD

**Issue by efl7a** [learn-co-curriculum/intro-to-redux-library-codealong#10]
This would have been very helpful information back in Using Redux with React.  It would have helped with debugging. Perhaps you can change the order.

**Comment by maxwellbenton** [comment]
Hi @efl7a,

Thanks for reporting this issue. We're now aware of it and are tracking this and other ordering issues in a new issue [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3).

We are currently updating and restructuring the materials in this section and will add this to our internal work queue. We will be updating the order of lessons in the next phase of this process and will take this information into consideration in upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when this issue is resolved.

Thanks for contributing!
