### ISSUE TITLE
ShoppingListItemReducer

### ISSUE THREAD

**Issue by AkaKuro4Ever** [learn-co-curriculum/intro-to-redux-library-codealong#12]
You should fix your code so that the return is not ```items: state.items.concat(state.items.length + 1)```, but:

``	switch (action.type) {
		case 'INCREASE_COUNT':
 			return Object.assign({}, state, {
 					items: state.items.concat(state.items.length + 1)
			});```

If not, the code in ```App``` will not work, for ```this.props.items``` will not exist after updating state.

**Comment by StephenArg** [comment]
I second this. Just found this bug today also.

**Comment by cdcardle** [comment]
Alternative to AkaKuro4Ever's suggestion:

return {
    ...state,
    items: state.items.concat(state.items.length + 1)
}

**Comment by blainelawson** [comment]
cdcardle's is the only one that works.

**Comment by maxwellbenton** [comment]
Hi @AkaKuro4Ever,

Thank you for opening this issue. We've updated this lesson's code snippets so that they correctly return a new object for the `INCREASE_COUNT` case, have made the examples consistent, and have updated the solution to reflect these changes. 

We apologize for any frustration this may have caused, but appreciate your feedback and help in improving our lessons for future students!
