### ISSUE TITLE
Same issue as #13 except the correct solution is this

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/intro-to-redux-library-codealong#16]
```const store = createStore(shoppingListItemReducer)

ReactDOM.render( <Provider store={store}>
  <App />
</Provider>,
  document.getElementById('root')
);

It's key that <App /> is on its own line. See this stackoverflow for more https://stackoverflow.com/questions/36735397/react-error-failed-proptype-invalid-prop-children-supplied-to-provider-ex

**Comment by SilverBright** [comment]
Thank you, this worked!

**Comment by maxwellbenton** [comment]
Hi @JoeQuattrone,

Thank you for opening this issue and providing a solution. We've updated this lesson so that it no longer produces an error due to the ReactDOM render statement.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
