### ISSUE TITLE
Return's an Array Instead of an Object 

### ISSUE THREAD

**Issue by jpavioli** [learn-co-curriculum/intro-to-redux-library-codealong#19]
Line 11 in the first "./src/reducers/shoppingListItemReducer.js" code block reads: 

return state.items.concat(state.items.length + 1);

The return line should return an object instead of an array... otherwise, it throws errors. (This is fixed in later code blocks)

**Comment by maxwellbenton** [comment]
Hi @jpavioli,

Thank you for opening this issue. We've updated this lesson's code snippets so that they correctly return a new object for the `INCREASE_COUNT` case, have made the examples consistent, and have updated the solution to reflect these changes. 

We apologize for any frustration this may have caused, but appreciate your feedback and help in improving our lessons for future students!
