### ISSUE TITLE
This lab was not clear and I was unable to follow along

### ISSUE THREAD

**Issue by minhl337** [learn-co-curriculum/intro-to-redux-library-codealong#20]
When following the lab, even copy and pasting from the code, my application still gave errors and was unable to run. I don't understand the information being presented.

**Comment by maxwellbenton** [comment]
Hi @minhl337,

Thank you for opening this issue. We've updated this lesson's code snippets and removed some errors that were preventing the code from running, which should resolve this issue for future students. We are also in the process of updating this section of content and are evaluating if this code-along needs to be moved to a different location in the materials so that students are better prepared.

We apologize for any frustration this may have caused, but appreciate your feedback and help in improving our lessons for future students!
