### ISSUE TITLE
ShoppingListItemReducer *still* causes failure

### ISSUE THREAD

**Issue by blainelawson** [learn-co-curriculum/intro-to-redux-library-codealong#23]
This issue was brought up in November of 2018 and has yet to be resolved. It does appear that someone attempted to resolve the error as the return of ShoppingListItemReducer mysteriously switches halfway through the lesson without mention:

  switch (action.type) {
    case 'INCREASE_COUNT':
      return state.items.concat(state.items.length + 1);
 
    default:
      return state;
  }

**to**

  switch (action.type) {
    case 'INCREASE_COUNT':
      console.log('Current state.items length %s', state.items.length);
      console.log('Updating state.items length to %s', state.items.length + 1);
      return Object.assign({}, state, {
        items: state.items.concat(state.items.length + 1)
      });
 
    default:
      console.log('Initial state.items length: %s', state.items.length);
      return state;
  }

**Note** ```return Object.assign({}...```

Unfortunately, this does not seem to be functional. The only code that works for me is:

	switch (action.type) {
	  case 'INCREASE_COUNT':
		return {
			...state,
			items: state.items.concat(state.items.length + 1)
			}   
	  default:
		return state;
	}

**Comment by maxwellbenton** [comment]
Hi @blainelawson,

Thank you for opening this issue. We've updated this lesson's code snippets so that they correctly return a new object for the `INCREASE_COUNT` case, have made the examples consistent, and have updated the solution to reflect these changes. 

We apologize for any frustration this may have caused, but appreciate your feedback and help in improving our lessons for future students!
